# Generated by Django 2.1.3 on 2019-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190112_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar01.jpg', upload_to='', verbose_name='Фотография'),
        ),
    ]
